/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ProtectedStaffRouteImport } from './routes/_protected/staff'
import { Route as ProtectedSettlementRouteImport } from './routes/_protected/settlement'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedPricingRouteImport } from './routes/_protected/pricing'
import { Route as ProtectedPlatformRouteImport } from './routes/_protected/platform'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAuditRouteImport } from './routes/_protected/audit'
import { Route as ProtectedAgreementRouteImport } from './routes/_protected/agreement'
import { Route as PublicSignUpRouteRouteImport } from './routes/_public/sign-up/route'
import { Route as PublicResetPasswordRouteRouteImport } from './routes/_public/reset-password/route'
import { Route as PublicFindRouteRouteImport } from './routes/_public/find/route'
import { Route as PublicSignUpIndexRouteImport } from './routes/_public/sign-up/index'
import { Route as PublicResetPasswordIndexRouteImport } from './routes/_public/reset-password/index'
import { Route as PublicFindIndexRouteImport } from './routes/_public/find/index'
import { Route as PublicSignUpVerifyEmailRouteImport } from './routes/_public/sign-up/verify-email'
import { Route as PublicSignUpTermRouteImport } from './routes/_public/sign-up/term'
import { Route as PublicSignUpOwnerCompleteRouteImport } from './routes/_public/sign-up/owner-complete'
import { Route as PublicSignUpMemberCompleteRouteImport } from './routes/_public/sign-up/member-complete'
import { Route as PublicSignUpInviteRouteImport } from './routes/_public/sign-up/invite'
import { Route as PublicSignUpFormRouteImport } from './routes/_public/sign-up/form'
import { Route as PublicSignUpEmailConfirmRouteImport } from './routes/_public/sign-up/email-confirm'
import { Route as PublicResetPasswordCompleteRouteImport } from './routes/_public/reset-password/complete'
import { Route as PublicFindPasswordRouteImport } from './routes/_public/find/password'
import { Route as PublicFindIdRouteImport } from './routes/_public/find/id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedStaffRoute = ProtectedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettlementRoute = ProtectedSettlementRouteImport.update({
  id: '/settlement',
  path: '/settlement',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPricingRoute = ProtectedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPlatformRoute = ProtectedPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAuditRoute = ProtectedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgreementRoute = ProtectedAgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicSignUpRouteRoute = PublicSignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRouteRoute =
  PublicResetPasswordRouteRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicFindRouteRoute = PublicFindRouteRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignUpIndexRoute = PublicSignUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicSignUpRouteRoute,
} as any)
const PublicResetPasswordIndexRoute =
  PublicResetPasswordIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicResetPasswordRouteRoute,
  } as any)
const PublicFindIndexRoute = PublicFindIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicFindRouteRoute,
} as any)
const PublicSignUpVerifyEmailRoute = PublicSignUpVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicSignUpRouteRoute,
} as any)
const PublicSignUpTermRoute = PublicSignUpTermRouteImport.update({
  id: '/term',
  path: '/term',
  getParentRoute: () => PublicSignUpRouteRoute,
} as any)
const PublicSignUpOwnerCompleteRoute =
  PublicSignUpOwnerCompleteRouteImport.update({
    id: '/owner-complete',
    path: '/owner-complete',
    getParentRoute: () => PublicSignUpRouteRoute,
  } as any)
const PublicSignUpMemberCompleteRoute =
  PublicSignUpMemberCompleteRouteImport.update({
    id: '/member-complete',
    path: '/member-complete',
    getParentRoute: () => PublicSignUpRouteRoute,
  } as any)
const PublicSignUpInviteRoute = PublicSignUpInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => PublicSignUpRouteRoute,
} as any)
const PublicSignUpFormRoute = PublicSignUpFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => PublicSignUpRouteRoute,
} as any)
const PublicSignUpEmailConfirmRoute =
  PublicSignUpEmailConfirmRouteImport.update({
    id: '/email-confirm',
    path: '/email-confirm',
    getParentRoute: () => PublicSignUpRouteRoute,
  } as any)
const PublicResetPasswordCompleteRoute =
  PublicResetPasswordCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => PublicResetPasswordRouteRoute,
  } as any)
const PublicFindPasswordRoute = PublicFindPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => PublicFindRouteRoute,
} as any)
const PublicFindIdRoute = PublicFindIdRouteImport.update({
  id: '/id',
  path: '/id',
  getParentRoute: () => PublicFindRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/find': typeof PublicFindRouteRouteWithChildren
  '/reset-password': typeof PublicResetPasswordRouteRouteWithChildren
  '/sign-up': typeof PublicSignUpRouteRouteWithChildren
  '/agreement': typeof ProtectedAgreementRoute
  '/audit': typeof ProtectedAuditRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/platform': typeof ProtectedPlatformRoute
  '/pricing': typeof ProtectedPricingRoute
  '/profile': typeof ProtectedProfileRoute
  '/settings': typeof ProtectedSettingsRoute
  '/settlement': typeof ProtectedSettlementRoute
  '/staff': typeof ProtectedStaffRoute
  '/login': typeof PublicLoginRoute
  '/find/id': typeof PublicFindIdRoute
  '/find/password': typeof PublicFindPasswordRoute
  '/reset-password/complete': typeof PublicResetPasswordCompleteRoute
  '/sign-up/email-confirm': typeof PublicSignUpEmailConfirmRoute
  '/sign-up/form': typeof PublicSignUpFormRoute
  '/sign-up/invite': typeof PublicSignUpInviteRoute
  '/sign-up/member-complete': typeof PublicSignUpMemberCompleteRoute
  '/sign-up/owner-complete': typeof PublicSignUpOwnerCompleteRoute
  '/sign-up/term': typeof PublicSignUpTermRoute
  '/sign-up/verify-email': typeof PublicSignUpVerifyEmailRoute
  '/find/': typeof PublicFindIndexRoute
  '/reset-password/': typeof PublicResetPasswordIndexRoute
  '/sign-up/': typeof PublicSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/agreement': typeof ProtectedAgreementRoute
  '/audit': typeof ProtectedAuditRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/platform': typeof ProtectedPlatformRoute
  '/pricing': typeof ProtectedPricingRoute
  '/profile': typeof ProtectedProfileRoute
  '/settings': typeof ProtectedSettingsRoute
  '/settlement': typeof ProtectedSettlementRoute
  '/staff': typeof ProtectedStaffRoute
  '/login': typeof PublicLoginRoute
  '/find/id': typeof PublicFindIdRoute
  '/find/password': typeof PublicFindPasswordRoute
  '/reset-password/complete': typeof PublicResetPasswordCompleteRoute
  '/sign-up/email-confirm': typeof PublicSignUpEmailConfirmRoute
  '/sign-up/form': typeof PublicSignUpFormRoute
  '/sign-up/invite': typeof PublicSignUpInviteRoute
  '/sign-up/member-complete': typeof PublicSignUpMemberCompleteRoute
  '/sign-up/owner-complete': typeof PublicSignUpOwnerCompleteRoute
  '/sign-up/term': typeof PublicSignUpTermRoute
  '/sign-up/verify-email': typeof PublicSignUpVerifyEmailRoute
  '/find': typeof PublicFindIndexRoute
  '/reset-password': typeof PublicResetPasswordIndexRoute
  '/sign-up': typeof PublicSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_public/find': typeof PublicFindRouteRouteWithChildren
  '/_public/reset-password': typeof PublicResetPasswordRouteRouteWithChildren
  '/_public/sign-up': typeof PublicSignUpRouteRouteWithChildren
  '/_protected/agreement': typeof ProtectedAgreementRoute
  '/_protected/audit': typeof ProtectedAuditRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/_protected/platform': typeof ProtectedPlatformRoute
  '/_protected/pricing': typeof ProtectedPricingRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/settlement': typeof ProtectedSettlementRoute
  '/_protected/staff': typeof ProtectedStaffRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/find/id': typeof PublicFindIdRoute
  '/_public/find/password': typeof PublicFindPasswordRoute
  '/_public/reset-password/complete': typeof PublicResetPasswordCompleteRoute
  '/_public/sign-up/email-confirm': typeof PublicSignUpEmailConfirmRoute
  '/_public/sign-up/form': typeof PublicSignUpFormRoute
  '/_public/sign-up/invite': typeof PublicSignUpInviteRoute
  '/_public/sign-up/member-complete': typeof PublicSignUpMemberCompleteRoute
  '/_public/sign-up/owner-complete': typeof PublicSignUpOwnerCompleteRoute
  '/_public/sign-up/term': typeof PublicSignUpTermRoute
  '/_public/sign-up/verify-email': typeof PublicSignUpVerifyEmailRoute
  '/_public/find/': typeof PublicFindIndexRoute
  '/_public/reset-password/': typeof PublicResetPasswordIndexRoute
  '/_public/sign-up/': typeof PublicSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find'
    | '/reset-password'
    | '/sign-up'
    | '/agreement'
    | '/audit'
    | '/dashboard'
    | '/onboarding'
    | '/platform'
    | '/pricing'
    | '/profile'
    | '/settings'
    | '/settlement'
    | '/staff'
    | '/login'
    | '/find/id'
    | '/find/password'
    | '/reset-password/complete'
    | '/sign-up/email-confirm'
    | '/sign-up/form'
    | '/sign-up/invite'
    | '/sign-up/member-complete'
    | '/sign-up/owner-complete'
    | '/sign-up/term'
    | '/sign-up/verify-email'
    | '/find/'
    | '/reset-password/'
    | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agreement'
    | '/audit'
    | '/dashboard'
    | '/onboarding'
    | '/platform'
    | '/pricing'
    | '/profile'
    | '/settings'
    | '/settlement'
    | '/staff'
    | '/login'
    | '/find/id'
    | '/find/password'
    | '/reset-password/complete'
    | '/sign-up/email-confirm'
    | '/sign-up/form'
    | '/sign-up/invite'
    | '/sign-up/member-complete'
    | '/sign-up/owner-complete'
    | '/sign-up/term'
    | '/sign-up/verify-email'
    | '/find'
    | '/reset-password'
    | '/sign-up'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_public/find'
    | '/_public/reset-password'
    | '/_public/sign-up'
    | '/_protected/agreement'
    | '/_protected/audit'
    | '/_protected/dashboard'
    | '/_protected/onboarding'
    | '/_protected/platform'
    | '/_protected/pricing'
    | '/_protected/profile'
    | '/_protected/settings'
    | '/_protected/settlement'
    | '/_protected/staff'
    | '/_public/login'
    | '/_public/'
    | '/_public/find/id'
    | '/_public/find/password'
    | '/_public/reset-password/complete'
    | '/_public/sign-up/email-confirm'
    | '/_public/sign-up/form'
    | '/_public/sign-up/invite'
    | '/_public/sign-up/member-complete'
    | '/_public/sign-up/owner-complete'
    | '/_public/sign-up/term'
    | '/_public/sign-up/verify-email'
    | '/_public/find/'
    | '/_public/reset-password/'
    | '/_public/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/staff': {
      id: '/_protected/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof ProtectedStaffRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settlement': {
      id: '/_protected/settlement'
      path: '/settlement'
      fullPath: '/settlement'
      preLoaderRoute: typeof ProtectedSettlementRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pricing': {
      id: '/_protected/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ProtectedPricingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/platform': {
      id: '/_protected/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof ProtectedPlatformRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/audit': {
      id: '/_protected/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof ProtectedAuditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agreement': {
      id: '/_protected/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof ProtectedAgreementRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/find': {
      id: '/_public/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof PublicFindRouteRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-up/': {
      id: '/_public/sign-up/'
      path: '/'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof PublicSignUpIndexRouteImport
      parentRoute: typeof PublicSignUpRouteRoute
    }
    '/_public/reset-password/': {
      id: '/_public/reset-password/'
      path: '/'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof PublicResetPasswordIndexRouteImport
      parentRoute: typeof PublicResetPasswordRouteRoute
    }
    '/_public/find/': {
      id: '/_public/find/'
      path: '/'
      fullPath: '/find/'
      preLoaderRoute: typeof PublicFindIndexRouteImport
      parentRoute: typeof PublicFindRouteRoute
    }
    '/_public/sign-up/verify-email': {
      id: '/_public/sign-up/verify-email'
      path: '/verify-email'
      fullPath: '/sign-up/verify-email'
      preLoaderRoute: typeof PublicSignUpVerifyEmailRouteImport
      parentRoute: typeof PublicSignUpRouteRoute
    }
    '/_public/sign-up/term': {
      id: '/_public/sign-up/term'
      path: '/term'
      fullPath: '/sign-up/term'
      preLoaderRoute: typeof PublicSignUpTermRouteImport
      parentRoute: typeof PublicSignUpRouteRoute
    }
    '/_public/sign-up/owner-complete': {
      id: '/_public/sign-up/owner-complete'
      path: '/owner-complete'
      fullPath: '/sign-up/owner-complete'
      preLoaderRoute: typeof PublicSignUpOwnerCompleteRouteImport
      parentRoute: typeof PublicSignUpRouteRoute
    }
    '/_public/sign-up/member-complete': {
      id: '/_public/sign-up/member-complete'
      path: '/member-complete'
      fullPath: '/sign-up/member-complete'
      preLoaderRoute: typeof PublicSignUpMemberCompleteRouteImport
      parentRoute: typeof PublicSignUpRouteRoute
    }
    '/_public/sign-up/invite': {
      id: '/_public/sign-up/invite'
      path: '/invite'
      fullPath: '/sign-up/invite'
      preLoaderRoute: typeof PublicSignUpInviteRouteImport
      parentRoute: typeof PublicSignUpRouteRoute
    }
    '/_public/sign-up/form': {
      id: '/_public/sign-up/form'
      path: '/form'
      fullPath: '/sign-up/form'
      preLoaderRoute: typeof PublicSignUpFormRouteImport
      parentRoute: typeof PublicSignUpRouteRoute
    }
    '/_public/sign-up/email-confirm': {
      id: '/_public/sign-up/email-confirm'
      path: '/email-confirm'
      fullPath: '/sign-up/email-confirm'
      preLoaderRoute: typeof PublicSignUpEmailConfirmRouteImport
      parentRoute: typeof PublicSignUpRouteRoute
    }
    '/_public/reset-password/complete': {
      id: '/_public/reset-password/complete'
      path: '/complete'
      fullPath: '/reset-password/complete'
      preLoaderRoute: typeof PublicResetPasswordCompleteRouteImport
      parentRoute: typeof PublicResetPasswordRouteRoute
    }
    '/_public/find/password': {
      id: '/_public/find/password'
      path: '/password'
      fullPath: '/find/password'
      preLoaderRoute: typeof PublicFindPasswordRouteImport
      parentRoute: typeof PublicFindRouteRoute
    }
    '/_public/find/id': {
      id: '/_public/find/id'
      path: '/id'
      fullPath: '/find/id'
      preLoaderRoute: typeof PublicFindIdRouteImport
      parentRoute: typeof PublicFindRouteRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAgreementRoute: typeof ProtectedAgreementRoute
  ProtectedAuditRoute: typeof ProtectedAuditRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
  ProtectedPlatformRoute: typeof ProtectedPlatformRoute
  ProtectedPricingRoute: typeof ProtectedPricingRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedSettlementRoute: typeof ProtectedSettlementRoute
  ProtectedStaffRoute: typeof ProtectedStaffRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAgreementRoute: ProtectedAgreementRoute,
  ProtectedAuditRoute: ProtectedAuditRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
  ProtectedPlatformRoute: ProtectedPlatformRoute,
  ProtectedPricingRoute: ProtectedPricingRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedSettlementRoute: ProtectedSettlementRoute,
  ProtectedStaffRoute: ProtectedStaffRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicFindRouteRouteChildren {
  PublicFindIdRoute: typeof PublicFindIdRoute
  PublicFindPasswordRoute: typeof PublicFindPasswordRoute
  PublicFindIndexRoute: typeof PublicFindIndexRoute
}

const PublicFindRouteRouteChildren: PublicFindRouteRouteChildren = {
  PublicFindIdRoute: PublicFindIdRoute,
  PublicFindPasswordRoute: PublicFindPasswordRoute,
  PublicFindIndexRoute: PublicFindIndexRoute,
}

const PublicFindRouteRouteWithChildren = PublicFindRouteRoute._addFileChildren(
  PublicFindRouteRouteChildren,
)

interface PublicResetPasswordRouteRouteChildren {
  PublicResetPasswordCompleteRoute: typeof PublicResetPasswordCompleteRoute
  PublicResetPasswordIndexRoute: typeof PublicResetPasswordIndexRoute
}

const PublicResetPasswordRouteRouteChildren: PublicResetPasswordRouteRouteChildren =
  {
    PublicResetPasswordCompleteRoute: PublicResetPasswordCompleteRoute,
    PublicResetPasswordIndexRoute: PublicResetPasswordIndexRoute,
  }

const PublicResetPasswordRouteRouteWithChildren =
  PublicResetPasswordRouteRoute._addFileChildren(
    PublicResetPasswordRouteRouteChildren,
  )

interface PublicSignUpRouteRouteChildren {
  PublicSignUpEmailConfirmRoute: typeof PublicSignUpEmailConfirmRoute
  PublicSignUpFormRoute: typeof PublicSignUpFormRoute
  PublicSignUpInviteRoute: typeof PublicSignUpInviteRoute
  PublicSignUpMemberCompleteRoute: typeof PublicSignUpMemberCompleteRoute
  PublicSignUpOwnerCompleteRoute: typeof PublicSignUpOwnerCompleteRoute
  PublicSignUpTermRoute: typeof PublicSignUpTermRoute
  PublicSignUpVerifyEmailRoute: typeof PublicSignUpVerifyEmailRoute
  PublicSignUpIndexRoute: typeof PublicSignUpIndexRoute
}

const PublicSignUpRouteRouteChildren: PublicSignUpRouteRouteChildren = {
  PublicSignUpEmailConfirmRoute: PublicSignUpEmailConfirmRoute,
  PublicSignUpFormRoute: PublicSignUpFormRoute,
  PublicSignUpInviteRoute: PublicSignUpInviteRoute,
  PublicSignUpMemberCompleteRoute: PublicSignUpMemberCompleteRoute,
  PublicSignUpOwnerCompleteRoute: PublicSignUpOwnerCompleteRoute,
  PublicSignUpTermRoute: PublicSignUpTermRoute,
  PublicSignUpVerifyEmailRoute: PublicSignUpVerifyEmailRoute,
  PublicSignUpIndexRoute: PublicSignUpIndexRoute,
}

const PublicSignUpRouteRouteWithChildren =
  PublicSignUpRouteRoute._addFileChildren(PublicSignUpRouteRouteChildren)

interface PublicRouteChildren {
  PublicFindRouteRoute: typeof PublicFindRouteRouteWithChildren
  PublicResetPasswordRouteRoute: typeof PublicResetPasswordRouteRouteWithChildren
  PublicSignUpRouteRoute: typeof PublicSignUpRouteRouteWithChildren
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicFindRouteRoute: PublicFindRouteRouteWithChildren,
  PublicResetPasswordRouteRoute: PublicResetPasswordRouteRouteWithChildren,
  PublicSignUpRouteRoute: PublicSignUpRouteRouteWithChildren,
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
