/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export type AccountProviderId = typeof AccountProviderId[keyof typeof AccountProviderId];


export const AccountProviderId = {
  credential: 'credential',
} as const;
