/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { AccountMetadata } from './accountMetadata';
import type { AccountProviderId } from './accountProviderId';
import type { User } from './user';

export interface Account {
  user: User;
  providerId: AccountProviderId;
  accountId: string;
  accessToken?: string;
  refreshToken?: string;
  accessTokenExpiresAt?: string;
  refreshTokenExpiresAt?: string;
  scope?: string;
  idToken?: string;
  password?: string;
  failCount: number;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: AccountMetadata;
}
