/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { ApiKeyMetadata } from './apiKeyMetadata';

export interface ApiKey {
  configId: string;
  referenceId: string;
  name?: string;
  start?: string;
  prefix?: string;
  key: string;
  refillInterval?: number;
  refillAmount?: number;
  lastRefillAt?: string;
  enabled: boolean;
  rateLimitEnabled: boolean;
  rateLimitTimeWindow?: number;
  rateLimitMax?: number;
  requestCount: number;
  remaining?: number;
  lastRequest?: string;
  expiresAt?: string;
  permissions?: string;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: ApiKeyMetadata;
}
