/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { AuditListResponseDto } from './auditListResponseDto';
import type { BaseResponse } from './baseResponse';

export type AuditControllerFindAll200 = BaseResponse & {
  data: AuditListResponseDto;
};
