/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

/**
 * 페이로드 (마스킹됨)
 * @nullable
 */
export type AuditPayload = { [key: string]: unknown } | null;
