/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export type AuditControllerFindAllParams = {
/**
 * 유저 ID로 검색
 * @minLength 1
 */
userId?: string;
/**
 * 조직 ID로 검색
 * @minLength 1
 */
organizationId?: string;
/**
 * URL로 검색
 * @minLength 1
 */
url?: string;
/**
 * 페이지 번호
 */
page?: number;
/**
 * 페이지당 항목 수
 */
limit?: number;
};
