/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { AuditListItemDto2 } from './auditListItemDto2';

export interface AuditListResponseDto2 {
  items: AuditListItemDto2[];
  total: number;
  page: number;
  limit: number;
}
