/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { AuditListItemDto } from './auditListItemDto';

export interface AuditListResponseDto {
  items: AuditListItemDto[];
  total: number;
  page: number;
  limit: number;
}
