/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface CreateAccountDto {
  name: string;
  email: string;
  phoneNumber: string;
  password: string;
  confirmPassword: string;
  /** @minItems 1 */
  termIds: string[];
}
