/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { CreateTermDtoTermType } from './createTermDtoTermType';

export interface CreateTermDto {
  termType: CreateTermDtoTermType;
  title: string;
  content: string;
  version: string;
  isActive?: boolean;
  startDate?: string;
  endDate?: string;
}
