/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface CreateSettlementDto {
  /** @minLength 1 */
  organizationId: string;
  amount: number;
}
