/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface Enable2FADto {
  /** 2FA 비밀키 */
  secret: string;
  /** 2FA 토큰 */
  token: string;
}
