/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface ErrorDetail {
  /**
   * 에러 발생 필드
   * @nullable
   */
  field?: string | null;
  /** 에러 이유 */
  reason: string;
}
