/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { GetTermsResponseDtoMetadata } from './getTermsResponseDtoMetadata';
import type { GetTermsResponseDtoTermType } from './getTermsResponseDtoTermType';
import type { Organization } from './organization';
import type { TermCategory } from './termCategory';

export interface GetTermsResponseDto {
  category: TermCategory;
  content: string;
  version: string;
  startDate: string;
  endDate: string;
  organization?: Organization;
  termType: GetTermsResponseDtoTermType;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: GetTermsResponseDtoMetadata;
  isActive: boolean;
  title: string;
  agreedAt?: string;
}
