/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { InviteStaffDtoRole } from './inviteStaffDtoRole';

export interface InviteStaffDto {
  email: string;
  /** @minLength 1 */
  name: string;
  role: InviteStaffDtoRole;
}
