/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export type InviteStaffDtoRole = typeof InviteStaffDtoRole[keyof typeof InviteStaffDtoRole];


export const InviteStaffDtoRole = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;
