/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { InviteStaffDto2Role } from './inviteStaffDto2Role';

export interface InviteStaffDto2 {
  role: InviteStaffDto2Role;
  email: string;
  /** @minLength 1 */
  name: string;
}
