/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { InvitationMetadata } from './invitationMetadata';
import type { InvitationRole } from './invitationRole';
import type { InvitationStatus } from './invitationStatus';
import type { Organization } from './organization';
import type { User } from './user';

export interface Invitation {
  inviter: User;
  organization: Organization;
  role: InvitationRole;
  status: InvitationStatus;
  email: string;
  expiresAt: string;
  name: string;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: InvitationMetadata;
}
