/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { LoginResponseDtoMetadata } from './loginResponseDtoMetadata';
import type { Member } from './member';
import type { Session } from './session';
import type { TermAgreement } from './termAgreement';

export interface LoginResponseDto {
  sessions: Session[];
  member?: Member;
  termAgreements: TermAgreement[];
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: LoginResponseDtoMetadata;
  name: string;
  email: string;
  emailVerified: boolean;
  image?: string;
  isAnonymous?: boolean;
  role?: string;
  banned?: boolean;
  banReason?: string;
  banExpires?: string;
  twoFactorEnabled?: boolean;
  phoneNumber?: string;
  phoneNumberVerified?: boolean;
}
