/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  accountId: string;
  password: string;
  /**
   * @minLength 6
   * @maxLength 6
   */
  token?: string;
}
