/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { MemberMetadata } from './memberMetadata';
import type { MemberRole } from './memberRole';
import type { Organization } from './organization';
import type { User } from './user';

export interface Member {
  organization: Organization;
  user: User;
  role: MemberRole;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: MemberMetadata;
}
