/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { Organization } from './organization';
import type { OrganizationRoleMetadata } from './organizationRoleMetadata';

export interface OrganizationRole {
  organization: Organization;
  role: string;
  permission: string;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: OrganizationRoleMetadata;
}
