/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { Member } from './member';
import type { OrganizationMetadataProperty } from './organizationMetadataProperty';
import type { OrganizationRole } from './organizationRole';

export interface Organization {
  members: Member[];
  roles: OrganizationRole[];
  name: string;
  slug: string;
  logo?: string;
  metadata?: OrganizationMetadataProperty;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
}
