/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { OrganizationMetadataType } from './organizationMetadataType';

export interface OrganizationMetadata {
  type: OrganizationMetadataType;
  trialExpiresAt?: string;
  isActive: boolean;
  activatedAt?: string;
  activationExpiresAt?: string;
  customDomain?: string;
  logoUrl?: string;
}
