/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { PlatformUsageDto2 } from './platformUsageDto2';

export interface PlatformStatusResponseDto {
  /** 조직 ID */
  id: string;
  /** 조직명 */
  name: string;
  /** 조직 슬러그 */
  slug: string;
  /** 활성화 여부 */
  isActive: boolean;
  /** 트라이얼 종료일 */
  trialExpiresAt?: string;
  /** 활성화 종료일 */
  activationExpiresAt?: string;
  /** 이용 현황 */
  usage: PlatformUsageDto2;
}
