/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { BaseResponse } from './baseResponse';
import type { PlatformStatusResponseDto } from './platformStatusResponseDto';

export type PlatformControllerGetStatus200 = BaseResponse & {
  data: PlatformStatusResponseDto;
};
