/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface PlatformStatsDto {
  /** Number of active tenants */
  activeTenants: number;
  /** Total revenue across all tenants */
  totalRevenue: number;
  /** Current platform health status */
  systemHealth: string;
  /** Number of pending settlements */
  pendingSettlements: number;
}
