/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface PlatformUsageDto2 {
  /** API 호출 수 */
  apiCalls: number;
  /** 저장 공간 사용량 (MB) */
  storageUsed: number;
  /** 마지막 계산 일시 */
  lastCalculatedAt: string;
}
