/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface PlatformPolicyResponseDto {
  /** API 호출 제한 */
  apiLimit: number;
  /** 저장 공간 제한 (MB) */
  storageLimit: number;
  /** 허용 기능 목록 */
  features: string[];
  /** 요금제 명칭 */
  planName: string;
}
