/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface ServicePlanResponseDto {
  name: string;
  monthlyPrice: number;
  features: string[];
  createdAt: string;
}
