/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { AuditListResponseDto2 } from './auditListResponseDto2';
import type { BaseResponse } from './baseResponse';

export type ServiceAuditControllerFindAll200 = BaseResponse & {
  data: AuditListResponseDto2;
};
