/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface ServiceSettlementResponseDto {
  id: string;
  amount: number;
  status: string;
  settledAt?: string;
  createdAt: string;
}
