/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export type ServiceAuditControllerFindAllParams = {
page?: number;
limit?: number;
/**
 * @minLength 1
 */
userId?: string;
/**
 * @minLength 1
 */
organizationId?: string;
/**
 * @minLength 1
 */
url?: string;
};
