/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { BaseResponse } from './baseResponse';
import type { LogoUploadResponseDto } from './logoUploadResponseDto';

export type ServiceSettingsControllerUploadLogoImage200 = BaseResponse & {
  data: LogoUploadResponseDto;
};
