/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface ServiceStatsDto2 {
  /** Total sales for the service */
  totalSales: number;
  /** Number of active staff members */
  activeStaff: number;
  /** Current platform usage metrics */
  platformUsage: number;
  /** Current subscription plan name */
  currentPlan: string;
}
