/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { Organization } from './organization';
import type { SessionMetadata } from './sessionMetadata';
import type { User } from './user';

export interface Session {
  user: User;
  activeOrganization?: Organization;
  token: string;
  expiresAt: string;
  ipAddress?: string;
  userAgent?: string;
  impersonatedBy?: string;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: SessionMetadata;
}
