/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface Setup2FAResponseDto {
  /** 2FA 비밀키 */
  secret: string;
  /** QR 코드 URL */
  url: string;
}
