/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

/**
 * 약관 유형 (필수/선택)
 */
export type SignInNewAgreementResponseDtoTermType = typeof SignInNewAgreementResponseDtoTermType[keyof typeof SignInNewAgreementResponseDtoTermType];


export const SignInNewAgreementResponseDtoTermType = {
  required: 'required',
  optional: 'optional',
} as const;
