/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { StaffResponseDto2Role } from './staffResponseDto2Role';
import type { StaffUserResponseDto2 } from './staffUserResponseDto2';

export interface StaffResponseDto2 {
  role: StaffResponseDto2Role;
  user: StaffUserResponseDto2;
  /** @minLength 1 */
  id: string;
  createdAt: string;
}
