/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export type StaffResponseDtoStatus = typeof StaffResponseDtoStatus[keyof typeof StaffResponseDtoStatus];


export const StaffResponseDtoStatus = {
  pending: 'pending',
  accepted: 'accepted',
  rejected: 'rejected',
  canceled: 'canceled',
} as const;
