/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface StaffUserResponseDto2 {
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name: string;
  email: string;
}
