/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export type TenantMetadataResponseDtoType = typeof TenantMetadataResponseDtoType[keyof typeof TenantMetadataResponseDtoType];


export const TenantMetadataResponseDtoType = {
  PLATFORM: 'PLATFORM',
  BUSINESS: 'BUSINESS',
} as const;
