/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { TenantMetadataResponseDto } from './tenantMetadataResponseDto';

export interface TenantResponseDto {
  metadata: TenantMetadataResponseDto;
  /** @minLength 1 */
  id: string;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  slug: string;
  memberCount: number;
  createdAt: string;
}
