/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { TenantMetadataResponseDtoType } from './tenantMetadataResponseDtoType';

export interface TenantMetadataResponseDto {
  type: TenantMetadataResponseDtoType;
  trialExpiresAt?: string;
  isActive: boolean;
  activatedAt?: string;
  activationExpiresAt?: string;
}
