/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export type TermResponseDtoTermType = typeof TermResponseDtoTermType[keyof typeof TermResponseDtoTermType];


export const TermResponseDtoTermType = {
  required: 'required',
  optional: 'optional',
} as const;
