/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { Organization } from './organization';
import type { Term } from './term';
import type { TermCategoryMetadata } from './termCategoryMetadata';
import type { TermCategoryTermType } from './termCategoryTermType';

export interface TermCategory {
  organization?: Organization;
  terms: Term[];
  termType: TermCategoryTermType;
  title: string;
  isActive: boolean;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: TermCategoryMetadata;
}
