/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { TermCategory } from './termCategory';
import type { TermMetadata } from './termMetadata';

export interface Term {
  category: TermCategory;
  content: string;
  version: string;
  startDate: string;
  endDate: string;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: TermMetadata;
}
