/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { Term } from './term';
import type { TermAgreementMetadata } from './termAgreementMetadata';
import type { User } from './user';

export interface TermAgreement {
  user: User;
  term: Term;
  agreedAt?: string;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: TermAgreementMetadata;
}
