/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { TwoFactorMetadata } from './twoFactorMetadata';
import type { User } from './user';

export interface TwoFactor {
  user: User;
  secret?: string;
  backupCodes?: string;
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: TwoFactorMetadata;
}
