/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface UpdatePlatformSettingsDto {
  /** Maintenance mode status */
  maintenanceMode?: boolean;
  /**
   * System notification message
   * @minLength 1
   */
  systemNotification?: string;
  /**
   * Allowed IP ranges for admin access
   * @minLength 1
   */
  allowedIpRanges?: string;
}
