/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateStaffDto2Role } from './updateStaffDto2Role';

export interface UpdateStaffDto2 {
  role: UpdateStaffDto2Role;
}
