/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateTenantDto {
  /** @minLength 1 */
  name?: string;
  isActive?: boolean;
  trialExpiresAt?: string;
}
