/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { UpdateTermDtoTermType } from './updateTermDtoTermType';

export interface UpdateTermDto {
  title?: string;
  content?: string;
  version?: string;
  termType?: UpdateTermDtoTermType;
  isActive?: boolean;
  startDate?: string;
  endDate?: string;
}
