/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export type UpdateStaffDto2Role = typeof UpdateStaffDto2Role[keyof typeof UpdateStaffDto2Role];


export const UpdateStaffDto2Role = {
  owner: 'owner',
  admin: 'admin',
  member: 'member',
} as const;
