/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */

export type UpdateTermDtoTermType = typeof UpdateTermDtoTermType[keyof typeof UpdateTermDtoTermType];


export const UpdateTermDtoTermType = {
  required: 'required',
  optional: 'optional',
} as const;
