/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Admin API
 * The Admin API description
 * OpenAPI spec version: 1.0
 */
import type { VerificationMetadata } from './verificationMetadata';

export interface Verification {
  id: string;
  createdAt: string;
  createdBy?: string;
  updatedAt: string;
  updatedBy?: string;
  deletedAt?: string;
  deletedBy?: string;
  metadata?: VerificationMetadata;
  identifier: string;
  value: string;
  verifiedAt?: string;
  expiresAt: string;
  throttleKey: string;
}
