/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface MikroOrmMigrations {
  executed_at: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string | null;
}

export interface PlatformAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  failCount: Generated<number>;
  id: string;
  idToken: string | null;
  metadata: Json | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  updatedBy: string | null;
  userId: string;
}

export interface PlatformApiKey {
  configId: string;
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  enabled: boolean;
  expiresAt: Timestamp | null;
  id: string;
  key: string;
  lastRefillAt: Timestamp | null;
  lastRequest: Timestamp | null;
  metadata: Json | null;
  name: string | null;
  permissions: string | null;
  prefix: string | null;
  rateLimitEnabled: boolean;
  rateLimitMax: number | null;
  rateLimitTimeWindow: number | null;
  referenceId: string;
  refillAmount: number | null;
  refillInterval: number | null;
  remaining: number | null;
  requestCount: number;
  start: string | null;
  updatedAt: Timestamp;
  updatedBy: string | null;
}

export interface PlatformAudit {
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  duration: number;
  error: string | null;
  id: string;
  ip: string | null;
  metadata: Json | null;
  method: string;
  organizationId: string | null;
  payload: Json | null;
  referer: string | null;
  responseData: Json | null;
  statusCode: number;
  updatedAt: Timestamp;
  updatedBy: string | null;
  url: string;
  userAgent: string | null;
  userId: string | null;
}

export interface PlatformInvitation {
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  email: string;
  expiresAt: Timestamp;
  id: string;
  inviterId: string;
  metadata: Json | null;
  name: string;
  organizationId: string;
  role: string;
  status: string;
  updatedAt: Timestamp;
  updatedBy: string | null;
}

export interface PlatformMember {
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  id: string;
  metadata: Json | null;
  organizationId: string;
  role: string;
  updatedAt: Timestamp;
  updatedBy: string | null;
  userId: string;
}

export interface PlatformOrganization {
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  id: string;
  logo: string | null;
  metadata: Json;
  name: string;
  slug: string;
  updatedAt: Timestamp;
  updatedBy: string | null;
}

export interface PlatformOrganizationRole {
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  id: string;
  metadata: Json | null;
  organizationId: string;
  permission: string;
  role: string;
  updatedAt: Timestamp;
  updatedBy: string | null;
}

export interface PlatformSession {
  activeOrganizationId: string | null;
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  expiresAt: Timestamp;
  id: string;
  impersonatedBy: string | null;
  ipAddress: string | null;
  metadata: Json | null;
  token: string;
  updatedAt: Timestamp;
  updatedBy: string | null;
  userAgent: string | null;
  userId: string;
}

export interface PlatformTerm {
  categoryId: string;
  content: string;
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  endDate: Timestamp;
  id: string;
  metadata: Json | null;
  startDate: Timestamp;
  updatedAt: Timestamp;
  updatedBy: string | null;
  version: string;
}

export interface PlatformTermAgreement {
  agreedAt: Timestamp | null;
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  id: string;
  metadata: Json | null;
  termId: string;
  updatedAt: Timestamp;
  updatedBy: string | null;
  userId: string;
}

export interface PlatformTermCategory {
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  id: string;
  isActive: Generated<boolean>;
  metadata: Json | null;
  organizationId: string | null;
  termType: string;
  title: string;
  updatedAt: Timestamp;
  updatedBy: string | null;
}

export interface PlatformTwoFactor {
  backupCodes: string | null;
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  id: string;
  metadata: Json | null;
  secret: string | null;
  updatedAt: Timestamp;
  updatedBy: string | null;
  userId: string;
}

export interface PlatformUser {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  isAnonymous: boolean | null;
  metadata: Json | null;
  name: string;
  phoneNumber: string | null;
  phoneNumberVerified: boolean | null;
  role: string | null;
  twoFactorEnabled: boolean | null;
  twoFactorSecret: string | null;
  updatedAt: Timestamp;
  updatedBy: string | null;
}

export interface PlatformVerification {
  createdAt: Timestamp;
  createdBy: string | null;
  deletedAt: Timestamp | null;
  deletedBy: string | null;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  metadata: Json | null;
  throttleKey: string;
  updatedAt: Timestamp;
  updatedBy: string | null;
  value: string;
  verifiedAt: Timestamp | null;
}

export interface DB {
  mikro_orm_migrations: MikroOrmMigrations;
  "platform.Account": PlatformAccount;
  "platform.ApiKey": PlatformApiKey;
  "platform.Audit": PlatformAudit;
  "platform.Invitation": PlatformInvitation;
  "platform.Member": PlatformMember;
  "platform.Organization": PlatformOrganization;
  "platform.OrganizationRole": PlatformOrganizationRole;
  "platform.Session": PlatformSession;
  "platform.Term": PlatformTerm;
  "platform.TermAgreement": PlatformTermAgreement;
  "platform.TermCategory": PlatformTermCategory;
  "platform.TwoFactor": PlatformTwoFactor;
  "platform.User": PlatformUser;
  "platform.Verification": PlatformVerification;
}
